// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type ChapterSummaryReq struct {
	Title   string `json:"title"`   // 篇章标题
	Content string `json:"content"` // 篇章文本
}

type ChapterSummaryResp struct {
	Summary string `json:"summary"` // 篇章总结
}

type WebsocketReq struct {
	Token string `form:"token"` // 用户token
}

type WebsocketResp struct {
}
