// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type Chapter struct {
	ID      int64  `json:"id,string"`       // 章节id
	NovelID int64  `json:"novel_id,string"` // 小说id
	Title   string `json:"title"`           // 章节标题
	Content string `json:"content"`         // 章节内容
	Summary string `json:"summary"`         // 章节简介
}

type ChapterLite struct {
	ID      int64  `json:"id,string"`       // 章节id
	NovelID int64  `json:"novel_id,string"` // 小说id
	Title   string `json:"title"`           // 章节标题
}

type Character struct {
	ID      int64  `json:"id,string"`       // 角色id
	NovelID int64  `json:"novel_id,string"` // 小说id
	Name    string `json:"name"`            // 角色名称
	Avatar  string `json:"avatar"`          // 角色头像
	Summary string `json:"summary"`         // 角色简介
}

type CharacterLite struct {
	ID      int64  `json:"id,string"`       // 角色id
	NovelID int64  `json:"novel_id,string"` // 小说id
	Name    string `json:"name"`            // 角色名称
}

type CreateChapterReq struct {
	NovelID string `json:"novel_id"` // 小说id
	Title   string `json:"title"`    // 章节标题
	Content string `json:"content"`  // 章节内容
	Summary string `json:"summary"`  // 章节简介
}

type CreateChapterResp struct {
	ID int64 `json:"id,string"` // 章节id
}

type CreateCharacterReq struct {
	NovelID string `json:"novel_id"` // 小说id
	Name    string `json:"name"`     // 角色名称
	Avatar  string `json:"avatar"`   // 角色头像
	Summary string `json:"summary"`  // 角色简介
}

type CreateCharacterResp struct {
	ID int64 `json:"id,string"` // 角色id
}

type CreateNovelReq struct {
	Title    string `json:"title"`     // 小说标题
	Avatar   string `json:"avatar"`    // 小说封面
	Summary  string `json:"summary"`   // 小说简介
	Status   int    `json:"status"`    // 小说状态
	IsPublic bool   `json:"is_public"` // 是否公开
}

type CreateNovelResp struct {
	ID int64 `json:"id,string"` // 小说id
}

type DeleteChapterReq struct {
	ID string `json:"id"` // 章节id
}

type DeleteChapterResp struct {
	Msg string `json:"msg"` // 成功或失败信息
}

type DeleteCharacterReq struct {
	ID string `json:"id"` // 角色id
}

type DeleteCharacterResp struct {
	Msg string `json:"msg"` // 成功或失败信息
}

type DeleteNovelReq struct {
	ID string `json:"id"` // 小说id
}

type DeleteNovelResp struct {
	Msg string `json:"msg"` // 成功或失败信息
}

type GetChapterListReq struct {
	NovelID string `form:"novel_id"` // 小说id
}

type GetChapterListResp struct {
	List []ChapterLite `json:"list"` // 章节列表
}

type GetChapterReq struct {
	ID string `form:"id"` // 章节id
}

type GetChapterResp struct {
	Chapter Chapter `json:"chapter"` // 章节信息
}

type GetCharacterListReq struct {
	NovelID string `form:"novel_id"` // 小说id
}

type GetCharacterListResp struct {
	List []CharacterLite `json:"list"` // 角色列表
}

type GetCharacterReq struct {
	ID string `form:"id"` // 角色id
}

type GetCharacterResp struct {
	Character Character `json:"character"` // 角色信息
}

type GetNovelReq struct {
	ID string `form:"id"` // 小说id
}

type GetNovelResp struct {
	Novel Novel `json:"novel"` // 小说信息
}

type Novel struct {
	ID       int64  `json:"id,string"`        // 小说id
	Title    string `json:"title"`            // 小说标题
	Avatar   string `json:"avatar"`           // 小说封面
	AuthorID int64  `json:"author_id,string"` // 作者id
	Summary  string `json:"summary"`          // 小说简介
	Status   int    `json:"status"`           // 小说状态
	IsPublic bool   `json:"is_public"`        // 是否公开
}

type UpdateChapterReq struct {
	ID      string `json:"id"`      // 章节id
	Title   string `json:"title"`   // 章节标题
	Content string `json:"content"` // 章节内容
	Summary string `json:"summary"` // 章节简介
}

type UpdateChapterResp struct {
	Msg string `json:"msg"` // 成功或失败信息
}

type UpdateCharacterReq struct {
	ID      string `json:"id"`      // 角色id
	Name    string `json:"name"`    // 角色名称
	Avatar  string `json:"avatar"`  // 角色头像
	Summary string `json:"summary"` // 角色简介
}

type UpdateCharacterResp struct {
	Msg string `json:"msg"` // 成功或失败信息
}

type UpdateNovelReq struct {
	ID       string `json:"id"`        // 小说id
	Title    string `json:"title"`     // 小说标题
	Avatar   string `json:"avatar"`    // 小说封面
	Summary  string `json:"summary"`   // 小说简介
	Status   int    `json:"status"`    // 小说状态
	IsPublic bool   `json:"is_public"` // 是否公开
}

type UpdateNovelResp struct {
	Msg string `json:"msg"` // 成功或失败信息
}
