// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: point.proto

package pointrpc

import (
	"context"

	"Ai-Novel/application/point/interfaces/rpc/point"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Ping = point.Ping
	Pong = point.Pong

	PointRpc interface {
		Ping(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	}

	defaultPointRpc struct {
		cli zrpc.Client
	}
)

func NewPointRpc(cli zrpc.Client) PointRpc {
	return &defaultPointRpc{
		cli: cli,
	}
}

func (m *defaultPointRpc) Ping(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	client := point.NewPointRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
