// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CaptchaReq struct {
	Email string `json:"email"` // 接受验证码的邮箱
}

type CaptchaResp struct {
	Msg string `json:"msg"` // 响应信息
}

type PingReq struct {
}

type PingResp struct {
	Msg string `json:"msg"` // 响应信息
}
