// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: point.proto

package point

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PointRpc_Ping_FullMethodName = "/point.point_rpc/ping"
)

// PointRpcClient is the client API for PointRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PointRpcClient interface {
	Ping(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type pointRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewPointRpcClient(cc grpc.ClientConnInterface) PointRpcClient {
	return &pointRpcClient{cc}
}

func (c *pointRpcClient) Ping(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, PointRpc_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointRpcServer is the server API for PointRpc service.
// All implementations must embed UnimplementedPointRpcServer
// for forward compatibility.
type PointRpcServer interface {
	Ping(context.Context, *Ping) (*Pong, error)
	mustEmbedUnimplementedPointRpcServer()
}

// UnimplementedPointRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPointRpcServer struct{}

func (UnimplementedPointRpcServer) Ping(context.Context, *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPointRpcServer) mustEmbedUnimplementedPointRpcServer() {}
func (UnimplementedPointRpcServer) testEmbeddedByValue()                  {}

// UnsafePointRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PointRpcServer will
// result in compilation errors.
type UnsafePointRpcServer interface {
	mustEmbedUnimplementedPointRpcServer()
}

func RegisterPointRpcServer(s grpc.ServiceRegistrar, srv PointRpcServer) {
	// If the following call pancis, it indicates UnimplementedPointRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PointRpc_ServiceDesc, srv)
}

func _PointRpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointRpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointRpc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointRpcServer).Ping(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

// PointRpc_ServiceDesc is the grpc.ServiceDesc for PointRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PointRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "point.point_rpc",
	HandlerType: (*PointRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ping",
			Handler:    _PointRpc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "point.proto",
}
