// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	ai "Ai-Novel/application/ai/interfaces/api/internal/handler/ai"
	"Ai-Novel/application/ai/interfaces/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LimiterMinute10},
			[]rest.Route{
				{
					// websocket接口
					Method:  http.MethodGet,
					Path:    "/ws",
					Handler: ai.WebsocketHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LimiterMinute},
			[]rest.Route{
				{
					// 生成小说篇章总结
					Method:  http.MethodPost,
					Path:    "/chapter-summary",
					Handler: ai.ChapterSummaryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/ai"),
	)
}
