// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: point.proto

package server

import (
	"context"

	"Ai-Novel/application/point/interfaces/rpc/internal/logic"
	"Ai-Novel/application/point/interfaces/rpc/internal/svc"
	"Ai-Novel/application/point/interfaces/rpc/point"
)

type PointRpcServer struct {
	svcCtx *svc.ServiceContext
	point.UnimplementedPointRpcServer
}

func NewPointRpcServer(svcCtx *svc.ServiceContext) *PointRpcServer {
	return &PointRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *PointRpcServer) Ping(ctx context.Context, in *point.Ping) (*point.Pong, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
