// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: user.proto

package userrpc

import (
	"context"

	"Ai-Novel/application/user/interfaces/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Ping = user.Ping
	Pong = user.Pong

	UserRpc interface {
		Ping(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	}

	defaultUserRpc struct {
		cli zrpc.Client
	}
)

func NewUserRpc(cli zrpc.Client) UserRpc {
	return &defaultUserRpc{
		cli: cli,
	}
}

func (m *defaultUserRpc) Ping(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
