// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	base "Ai-Novel/application/user/interfaces/api/internal/handler/base"
	"Ai-Novel/application/user/interfaces/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware},
			[]rest.Route{
				{
					// 测试接口(ping)
					Method:  http.MethodGet,
					Path:    "/ping",
					Handler: base.PingHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/base"),
	)
}
